[package]
name = "kind2_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kind2_book = { path = "../book" }
hvm = "0.1.81"